Repository pagopa/pdnd-interop-uservice-party-management, pull requests merged in 2021-12, with the labels that each got.

#37 PIN-798 added contract data to token
  src/main/protobuf/v1/token.proto
  src/main/resources/interface-specification.yml
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/package.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/model/party/Token.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/model/persistence/serializer/v1/utils.scala
  src/test/scala/it/pagopa/pdnd/interop/uservice/partymanagement/PartyApiServiceSpec.scala
  src/test/scala/it/pagopa/pdnd/interop/uservice/partymanagement/TokenApiServiceData.scala
  src/test/scala/it/pagopa/pdnd/interop/uservice/partymanagement/package.scala
Labels: task

#39 fixed file manager
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/PartyApiServiceImpl.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/common/system/ApplicationConfiguration.scala
Labels: enhancement

#42 PIN-727 adding JWT validation layer
  kubernetes/config
  kubernetes/deployment.yaml.template
  project/Dependencies.scala
  src/main/protobuf/v1/events.proto
  src/main/resources/application-standalone.conf
  src/main/resources/application.conf
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/server/impl/Main.scala
Labels: task

#44 PIN 861: fix conflict error in createOrganization
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/PartyApiServiceImpl.scala
Labels: bug

#45 PIN 862: fix creation relationship response
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/PartyApiServiceImpl.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/error/RelationshipAlreadyExists.scala
  src/test/scala/it/pagopa/pdnd/interop/uservice/partymanagement/PartyApiServiceSpec.scala
Labels: bug

#46 setting up logging
  project/Dependencies.scala
  project/Versions.scala
  project/plugins.sbt
  src/main/resources/application-standalone.conf
  src/main/resources/logback.xml
  src/main/resources/reference.conf
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/HealthServiceApiImpl.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/PartyApiServiceImpl.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/model/persistence/PartyPersistentBehavior.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/model/persistence/State.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/server/impl/Main.scala
  template/scala-akka-http-server/api.mustache
  template/scala-akka-http-server/controller.mustache
Labels: task

#50 SELC 316: fix role match in PersistedPartyRelationship.create function
  src/main/resources/application-standalone.conf
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/model/party/PersistedPartyRelationship.scala
Labels: bug

#51 PIN-865 replacing openapi4j with swagger-request-validator
  project/Dependencies.scala
  project/Versions.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/HealthApiMarshallerImpl.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/api/impl/PartyApiMarshallerImpl.scala
  src/main/scala/it/pagopa/pdnd/interop/uservice/partymanagement/server/impl/Main.scala
  src/test/scala/it/pagopa/pdnd/interop/uservice/partymanagement/PartyApiServiceSpec.scala
  template/scala-akka-http-server/controller.mustache
Labels: task

#54 PIN-671 - improved error response serializations for upstream errors
  template/scala-akka-http-client/apiInvoker.mustache
Labels: enhancement, task

#55 PIN-913 - api invoke method made more robust
  project/Dependencies.scala
  template/scala-akka-http-client/apiInvoker.mustache
Labels: enhancement, task
